export const dayMap = {
  1: 'dayOne',
  2: 'dayTwo',
  3: 'dayThree',
  4: 'dayFour',
  5: 'dayFive',
  6: 'daySix',
  7: 'daySeven',
  8: 'dayEight',
  9: 'dayNine',
  10: 'dayTen',
  11: 'dayEleven',
  12: 'dayTwelve',
  13: 'dayThirteen',
  14: 'dayFourteen',
  15: 'dayFifteen',
  16: 'daySixteen',
  17: 'daySeventeen',
  18: 'dayEighteen',
  19: 'dayNineteen',
  20: 'dayTwenty',
  21: 'dayTwentyOne',
  22: 'dayTwentyTwo',
  23: 'dayTwentyThree',
  24: 'dayTwentyFour',
  25: 'dayTwentyFive',
} as const;
